import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';

const UserRegister = () => {
  // Stats data - will be replaced by API call
  const [stats, setStats] = useState({
    totalUsers: 21,
    totalAdmins: 2,
    totalOphthalmologists: 19
  });

  const [formData, setFormData] = useState({
    name: '',
    email: '',
    profession: '',
    role: '',
    userId: '194120062210', // This would be generated by backend
    sendEmail: true
  });

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData({
      ...formData,
      [name]: type === 'checkbox' ? checked : value
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Example of API call (you can replace this with your actual backend call)
    console.log('Form submitted:', formData);
    
    // Example of API call:
    // try {
    //   await registerUser(formData);
    //   // Reset form or redirect
    // } catch (error) {
    //   console.error('Error registering user:', error);
    // }
  };

  // Load stats when component mounts
  useEffect(() => {
    // Replace with actual API call for stats
    // const fetchStats = async () => {
    //   try {
    //     const response = await getDashboardStats();
    //     setStats(response.data);
    //   } catch (error) {
    //     console.error('Error fetching stats:', error);
    //   }
    // };
    // fetchStats();
  }, []);

  return (
    <div className="bg-gradient-to-br from-blue-100 to-blue-300 min-h-screen relative overflow-hidden">
      {/* Navbar */}
      <header className="py-2 bg-very-dark-secondary dark:bg-very-dark-secondary fixed top-0 left-0 right-0 z-50 p-4 shadow-md flex justify-between items-center">
        <div className="flex items-center">
          <img src="/microscope-icon.png" alt="OCTsense" className="h-8 mr-2" />
          <h1 className="text-white text-2xl font-bold">OCTsense</h1>
        </div>
        <nav className="flex space-x-4">
          <Link to="/" className="text-white hover:underline">Inicio</Link>
          <Link to="/usuarios" className="text-white hover:underline">Usuarios</Link>
          <Link to="/registrar" className="text-white hover:underline">Registrar</Link>
          <Link to="/editar" className="text-white hover:underline">Editar</Link>
          <Link to="/profile" className="text-white hover:underline">Perfil</Link>
        </nav>
      </header>

      {/* Contenido principal */}
      <div className="max-w-7xl mx-auto px-6 py-20 relative z-10">
        {/* Título */}
        <h2 className="text-4xl font-bold text-blue-800 mb-6">Registrar Usuario</h2>

        {/* Tarjetas de estadísticas */}
        <div className="grid md:grid-cols-3 gap-6 mb-10">
          <div className="bg-white rounded-2xl shadow-lg p-6 text-center">
            <p className="text-gray-600 text-sm">Total Usuarios</p>
            <p className="text-3xl font-bold text-blue-800">{stats.totalUsers}</p>
          </div>
          <div className="bg-white rounded-2xl shadow-lg p-6 text-center">
            <p className="text-gray-600 text-sm">Total Administradores</p>
            <p className="text-3xl font-bold text-blue-800">{stats.totalAdmins}</p>
          </div>
          <div className="bg-white rounded-2xl shadow-lg p-6 text-center">
            <p className="text-gray-600 text-sm">Total Profesionales</p>
            <p className="text-3xl font-bold text-blue-800">{stats.totalOphthalmologists}</p>
          </div>
        </div>

        {/* Formulario de registro */}
        <form onSubmit={handleSubmit} className="bg-white rounded-2xl shadow-lg p-6 max-w-3xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block text-gray-700 mb-2">Nombre</label>
              <input
                type="text"
                name="name"
                className="w-full p-2 rounded border"
                placeholder="Nombre completo"
                onChange={handleChange}
              />
            </div>
            <div>
              <label className="block text-gray-700 mb-2">Correo</label>
              <input
                type="email"
                name="email"
                className="w-full p-2 rounded border"
                placeholder="correo@ejemplo.com"
                onChange={handleChange}
              />
            </div>
          </div>

          <div className="mb-4">
            <label className="block text-gray-700 mb-2">Rol</label>
            <select
              name="role"
              className="w-full p-2 rounded border"
              onChange={handleChange}
            >
              <option value="">Seleccionar rol</option>
              <option value="Admin">Administrador</option>
              <option value="Normal">Usuario</option>
              <option value="Profesional">Profesional</option>
            </select>
          </div>

          <div className="mb-4">
            <p className="text-sm text-gray-700">
              Se enviará un correo al usuario para asignar una contraseña.
            </p>
          </div>

          <button
            type="submit"
            className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg transition-all"
          >
            Registrar
          </button>
        </form>
      </div>
    </div>
  );
};

export default UserRegister;